### ISSUE TITLE
Method Nack, Ack in public API

### ISSUE THREAD

**Issue by gustavodecarlo** [pedrokiefer/aiostomp#9]
That's not a issue, but a feature. Can put methods nack a ack in public API?

**Comment by krishna-kashyap** [comment]
@gustavodecarlo Very valid point, for better control on consumption in the application (message distribution is based on free client which in turn is based on ACK signalling message/s are consumed) it'd be good to expose ACK and NACK in public API.

@pedrokiefer Your thoughts on this?

**Comment by pedrokiefer** [comment]
Yes, Ack / Nack methods should be on public API. I'll try to add them tomorrow, time permitting.

**Comment by gustavodecarlo** [comment]
Thanks all, I'm coded that, but not test I can try a merge request, if guys
like?

Thanks!

**Comment by pedrokiefer** [comment]
Sure! 👍

**Comment by pedrokiefer** [comment]
Fixed with version 1.6.0 (975c7d744d3450283fd58a71d59aa9ca9278a6a1).
